### ISSUE TITLE
Python error if expected .ppr file is missing

### ISSUE THREAD

**Issue by KennethNielsen** [pyg3t/poproofread#4]
1) Open test.po
2) Edit
3) Quit
4) delete file test.po.ppr
5) start poproofread again
6) open test.po.ppr.out
7) You get this python error:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/poproofread/poproofread_gtk.py", line 186, in on_filechooser
    actual_file = self.ppr.open(filename)
  File "/usr/lib/pymodules/python2.7/poproofread/core.py", line 34, in open
    self.content, actual_file = self.fileio.read(filename)
  File "/usr/lib/pymodules/python2.7/poproofread/fileio.py", line 40, in read
    content = self.__read_ppr(os.path.splitext(input_file)[0])
  File "/usr/lib/pymodules/python2.7/poproofread/fileio.py", line 66, in __read_ppr
    self.__check_ppr_and_out_file(self.ppr_file, self.out_file, True)
  File "/usr/lib/pymodules/python2.7/poproofread/fileio.py", line 95, in __check_ppr_and_out_file
    raise FileError(ppr_file, 'The file does not exist.')
poproofread.custom_exceptions.FileError

---

Imported from Launchpad using lp2gh.
- date created: 2011-12-23T15:44:47Z
- owner: byrial-t
- assignee: k-nielsen81
- the launchpad url was https://bugs.launchpad.net/bugs/908158

**Comment by KennethNielsen** [comment]
(by k-nielsen81)
Hallo Byrial

Thanks for reporting this. This python error is actually the a custom poproofread exception that is being raised by poproofread so that it can be catched on a higher level in the program, and the information can be displayed to the user. Catching the exception and displaying the information has not yet been implemented and I'll tag it for version 0.1.8.

Regards Kenneth

**Comment by KennethNielsen** [comment]
(by k-nielsen81)
Fixed in revision 87.
